services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: zenticket_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DATABASE_NAME:-zenticket}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-symfony}
      MYSQL_USER: ${DATABASE_USER:-symfony}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/zenticket_backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zenticket_network

  # Serveur PHP-FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: zenticket_php
    depends_on:
      - database
    volumes:
      - ./:/var/www/symfony
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - zenticket_network

  # Serveur Web Nginx
  nginx:
    image: nginx:alpine
    container_name: zenticket_nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zenticket_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: zenticket_phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root}
    networks:
      - zenticket_network

  # Node.js pour les assets
  node:
    image: node:18-alpine
    container_name: zenticket_node
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    command: tail -f /dev/null
    networks:
      - zenticket_network
      
  # Serveur Mercure
  mercure:
    image: dunglas/mercure
    container_name: zenticket_mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}'
      CORS_ALLOWED_ORIGINS: '*'
      PUBLISH_ALLOWED_ORIGINS: '*'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    ports:
      - "3000:3000"
    volumes:
      - mercure_data:/data
    networks:
      - zenticket_network

volumes:
  db_data:
  mercure_data:

networks:
  zenticket_network:
    driver: bridge
